let step=1;const totalSteps=5;
function showStep(){document.querySelectorAll('.fitness-step').forEach(x=>x.classList.remove('active'));document.querySelector(`[data-step="${step}"]`).classList.add('active');document.getElementById('progress').style.width=(step/totalSteps*100)+'%';document.getElementById('progressText').textContent=`Bước ${step}/${totalSteps}`;document.getElementById('back').style.visibility=step===1?'hidden':'visible';document.getElementById('next').textContent=step===totalSteps?'Phân tích & tạo lịch tập':'Tiếp tục →'}
function radio(name){return document.querySelector(`input[name="${name}"]:checked`)?.value||''}
function nextStep(){if(step===1&&(!age.value||!height.value||!weight.value||!activity.value))return toast('Hãy nhập đủ thông tin cơ bản');if(step===3&&!radio('goal'))return toast('Hãy chọn mục tiêu tập luyện');if(step===4&&!experience.value)return toast('Hãy chọn kinh nghiệm tập luyện');if(step<totalSteps){step++;showStep();scrollTo({top:170,behavior:'smooth'})}else generatePlan()}
function prevStep(){if(step>1){step--;showStep()}}
document.querySelectorAll('input[name="injury"]').forEach(x=>x.addEventListener('change',()=>{injuryAreaWrap.style.display=radio('injury')==='yes'?'block':'none'}));
function bmi(w,h){return (w/Math.pow(h/100,2)).toFixed(1)}
function safety(d){if(d.chest==='yes'||d.faint==='yes'||d.breath==='yes')return{level:'stop',title:'Nên được đánh giá sức khỏe trước khi tập cường độ cao',text:'Bạn đã chọn ít nhất một dấu hiệu cần thận trọng như đau ngực, ngất/chóng mặt nghiêm trọng hoặc khó thở bất thường. Hệ thống sẽ không tạo lịch tập nặng tự động.',allow:false};if(d.injury==='yes')return{level:'caution',title:'Có thể cần điều chỉnh do chấn thương/khó chịu',text:'Chương trình chỉ nên dùng làm tham khảo. Tránh mọi động tác làm đau tăng lên và cân nhắc hỗ trợ chuyên môn nếu triệu chứng kéo dài.',allow:true};return{level:'safe',title:'Không ghi nhận dấu hiệu cảnh báo rõ ràng trong bảng hỏi',text:'Bạn vẫn nên bắt đầu ở mức phù hợp, chú ý kỹ thuật và dừng tập nếu xuất hiện triệu chứng bất thường.',allow:true}}
const library={full:[['Goblet Squat','3 × 8-12'],['Chest Press / Push-up','3 × 8-12'],['Lat Pulldown / Row','3 × 8-12'],['Romanian Deadlift','3 × 8-12'],['Shoulder Press','2 × 10-12'],['Plank','3 × 30-45 giây']],upper:[['Chest Press','3 × 8-12'],['Lat Pulldown','3 × 8-12'],['Dumbbell Row','3 × 10-12'],['Shoulder Press','3 × 8-12'],['Biceps Curl','2 × 10-15'],['Triceps Extension','2 × 10-15']],lower:[['Squat','3 × 8-12'],['Romanian Deadlift','3 × 8-12'],['Reverse Lunge','3 × 8-10 mỗi bên'],['Hip Thrust','3 × 10-15'],['Calf Raise','3 × 15-20']],cardio:[['Đi bộ nhanh / Jog nhẹ','20-35 phút'],['Bike / Elliptical','15-25 phút'],['Core circuit','8-12 phút']],mobility:[['Cat-Cow','2 × 8-10'],['Hip Flexor Stretch','2 × 30 giây/bên'],['Thoracic Rotation','2 × 8/bên'],['Deep Squat Hold','3 × 20-30 giây'],['Hamstring Stretch','2 × 30 giây']]};
function schedule(d){const days=+d.days;let base;if(d.goal==='muscle')base=[['Upper Body','upper'],['Lower Body','lower'],['Upper Body','upper'],['Lower Body','lower'],['Full Body bổ trợ','full'],['Mobility nhẹ','mobility']];else if(d.goal==='fatloss')base=[['Full Body','full'],['Cardio','cardio'],['Full Body','full'],['Cardio + Core','cardio'],['Full Body','full'],['Mobility','mobility']];else if(d.goal==='endurance')base=[['Cardio nền tảng','cardio'],['Full Body','full'],['Cardio biến tốc nhẹ','cardio'],['Full Body nhẹ','full'],['Cardio dài','cardio'],['Mobility','mobility']];else if(d.goal==='mobility')base=[['Mobility toàn thân','mobility'],['Core + Mobility','mobility'],['Đi bộ + Mobility','mobility'],['Full Body nhẹ','full'],['Mobility','mobility']];else base=[['Full Body','full'],['Cardio + Mobility','cardio'],['Full Body','full'],['Mobility','mobility'],['Full Body nhẹ','full']];return base.slice(0,days)}
function intensity(d){if(d.experience==='beginner'||d.activity==='low'||d.sleep==='low'||d.energy==='low')return'Nhẹ đến trung bình';if(d.experience==='advanced')return'Trung bình đến khá cao';return'Trung bình'}
function goalName(g){return{muscle:'Tăng cơ',fatloss:'Giảm mỡ',endurance:'Tăng sức bền',fitness:'Cải thiện thể lực',mobility:'Tăng linh hoạt'}[g]||'Thể lực'}
function injuryNote(area){return{knee:'Giảm/đổi các bài gây đau gối; có thể giảm biên độ squat/lunge.',back:'Tránh bài làm đau lưng tăng; ưu tiên kiểm soát thân người và tải nhẹ.',shoulder:'Tránh press overhead nếu đau; thử biến thể không đau.',ankle:'Hạn chế chạy/nhảy nếu cổ chân chưa ổn định.',wrist:'Có thể dùng tay cầm hoặc máy để giảm khó chịu cổ tay.',other:'Tránh động tác làm triệu chứng tăng.'}[area]||'Tránh các động tác làm đau tăng.'}
function generatePlan(){const d={age:+age.value,height:+height.value,weight:+weight.value,activity:activity.value,chest:radio('chest'),faint:radio('faint'),breath:radio('breath'),injury:radio('injury'),injuryArea:injuryArea.value,goal:radio('goal'),experience:experience.value,days:days.value,duration:duration.value,location:locationSel.value,sleep:sleep.value,energy:energy.value};localStorage.setItem('sporthub_fitness_profile',JSON.stringify(d));const s=safety(d),sch=schedule(d);let html=`<div class="section-heading"><div><span class="eyebrow">PERSONAL FITNESS PLAN</span><h2>Kế hoạch tập luyện tham khảo</h2><p>Được tạo từ câu trả lời trong Fitness Check.</p></div></div><div class="result-grid"><div class="result-stat"><span>Mục tiêu</span><strong>${goalName(d.goal)}</strong></div><div class="result-stat"><span>Số buổi</span><strong>${d.days}/tuần</strong></div><div class="result-stat"><span>Thời gian</span><strong>${d.duration} phút</strong></div><div class="result-stat"><span>Cường độ</span><strong>${intensity(d)}</strong></div></div><div class="safety-box ${s.level}"><h3>${s.title}</h3><p>${s.text}</p></div><div class="bmi-box"><span class="eyebrow">BMI THAM KHẢO</span><h2 style="color:var(--lime);font-size:36px">${bmi(d.weight,d.height)}</h2><p style="color:#9aacb3">BMI chỉ dựa trên chiều cao và cân nặng, không phải chẩn đoán sức khỏe hay đo thành phần cơ thể.</p></div>`;if(s.allow){html+=`<h2 style="margin-top:38px">Lịch tập ${d.days} buổi</h2><div class="workout-grid">${sch.map((day,i)=>`<div class="workout-day"><span class="eyebrow">BUỔI ${i+1}</span><h3>${day[0]}</h3>${library[day[1]].map(e=>`<div class="exercise"><strong>${e[0]}</strong><span>${e[1]}</span></div>`).join('')}</div>`).join('')}</div>`;if(d.injury==='yes')html+=`<div class="safety-box caution"><h3>Điều chỉnh do chấn thương/khó chịu</h3><p>${injuryNote(d.injuryArea)}</p></div>`;html+=`<h2 style="margin-top:42px">Cách áp dụng</h2><div class="guide-grid"><div class="guide-card"><h3>1. Khởi động</h3><p>5-10 phút vận động nhẹ và 1-3 set khởi động cho bài chính.</p></div><div class="guide-card"><h3>2. Giữ kỹ thuật</h3><p>Dừng hiệp khi kỹ thuật xuống rõ rệt; người mới nên còn khoảng 2-3 rep dự phòng.</p></div><div class="guide-card"><h3>3. Tăng dần</h3><p>Khi đạt đầu trên khoảng rep với kỹ thuật tốt nhiều buổi, tăng tải nhỏ.</p></div><div class="guide-card"><h3>4. Phục hồi</h3><p>Ngủ, ăn uống và ngày nghỉ là một phần của chương trình.</p></div></div>`}html+=`<div class="safety-box" style="margin-top:35px"><h3>Lưu ý</h3><p>Fitness Check không chẩn đoán bệnh và không thay thế bác sĩ, chuyên gia vật lý trị liệu hoặc huấn luyện viên có chuyên môn.</p></div>`;fitnessResultContent.innerHTML=html;fitnessResult.classList.add('active');fitnessResult.scrollIntoView({behavior:'smooth'})}
showStep();
